name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest


    steps:
    - uses: actions/checkout@v2
    - name: Xcodebuild Test
      run: xcodebuild clean test -project MemoryLane.xcodeproj -scheme MemoryLane -destination "platform=iOS Simulator,name=iPad (8th generation)"
