name: Build Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest


    steps:
    - uses: actions/checkout@v2
    - name: CocoaPod Install
      run: pod install
    - name: Force xcode 12
      run: sudo xcode-select -switch /Applications/Xcode_12.app
    - name: Xcodebuild Test
      run: xcodebuild clean test -workspace MemoryLane.xcworkspace -scheme MemoryLane -destination "platform=iOS Simulator,name=iPad (8th generation)"
